apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-string-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-string-generator
  template:
    metadata:
      labels:
        app: flask-app-string-generator
    spec:
      containers:
        - name: flask-app-string-generator
          image: dpuertamartos/flask-app