apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-app-string-generator-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi