apiVersion: v1
kind: Service
metadata:
  namespace: string-ns
  name: flask-app-string-generator-svc
spec:
  type: ClusterIP
  selector:
    app: flask-app-string-generator
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 5000