apiVersion: v1
kind: Service
metadata:
  namespace: string-ns
  name: flask-app-counter-svc
spec:
  type: ClusterIP
  selector:
    app: flask-app-counter
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 5001