apiVersion: v1
kind: Service
metadata:
  namespace: string-ns
  name: postgres-pingpong-svc
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      name: db
      protocol: TCP
      targetPort: 5432
---
# A ConfigMap that creates the schema for the 'pingpongers' table
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: string-ns
  name: postgres-pingpong-seed
data:
  seed.sql: |
    CREATE TABLE counter (id SERIAL PRIMARY KEY, count INTEGER NOT NULL);
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: string-ns
  name: postgres-pingpong-stateful
spec:
  serviceName: postgres-pingpong-svc
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: db
          image: postgres:10-alpine
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          envFrom:
            - secretRef:
                name: postgres-pw
          ports:
            - name: db
              containerPort: 5432
          volumeMounts:
            # mountpoint to store pg data
            - name: data
              mountPath: /var/lib/postgresql/data/
            - name: postgres-pingpong-seed
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-pingpong-seed
          configMap:
            name: postgres-pingpong-seed
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
